[tool.poetry]
name = "TestRCCA"
version = "0.1.0"
description = ""
authors = ["Yanis Mammar <yanis.mammar@epita.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
